version: "3.8"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./api/:/app
  db:
    container_name: db
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password